#!/usr/bin/env php
<?php
/**
 * entry file for qin app
 *
 * @var Qin\Console\App $app
 * @var Toolkit\DI\Container $di
 */

define('RUN_MODE',  'cli');

require __DIR__ . '/vendor/autoload.php';
include __DIR__ . '/conf/defined.php';

// boot
$app = \App\Bootstrap::boot();

// in the unit testing.
if (IN_UNIT_TESTING) {
  return $app;
}

require __DIR__ . '/app/Console/routes.php';

$app->run();
